name: firebase_playground
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  firebase_core: ^2.30.1
  firebase_analytics: ^10.10.4
  firebase_messaging: ^14.9.1
  cloud_firestore: ^4.17.2

  go_router: ^14.0.2
  hooks_riverpod: ^3.0.0-dev.3
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^3.0.0-dev.3
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.1.1
  cloud_firestore_odm: ^1.0.0-dev.84
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^3.0.0-dev.11
  build_runner: ^2.4.9
  custom_lint: ^0.5.11
  riverpod_lint: ^3.0.0-dev.4
  cloud_firestore_odm_generator: ^1.0.0-dev.85
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
