name: firebase_playground
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  firebase_core: ^3.8.0
  firebase_analytics: ^11.3.5
  firebase_messaging: ^15.1.5
  cloud_firestore: ^5.5.0
  cloud_firestore_odm: ^1.0.0-dev.88
  firebase_data_connect: ^0.1.2+4

  go_router: ^14.6.1
  hooks_riverpod: ^3.0.0-dev.3
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^3.0.0-dev.3
  permission_handler: ^11.3.0
  flutter_local_notifications: ^18.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  uuid: ^4.5.1
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0-dev.11
  build_runner: ^2.4.13
  custom_lint: ^0.5.11
  riverpod_lint: ^3.0.0-dev.4
  cloud_firestore_odm_generator: ^1.0.0-dev.89
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
